version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017
  gcintenv:
    depends_on:
      - mongo
    image: ghcr.io/ciocoa/gcintenv
    restart: always
    ports:
      - 80:80
      - 443:443
      - 22102:22102/udp
    volumes:
      - ./plugins:/root/plugins
    environment:
      GC_TZ: Asia/Shanghai
      GC_PLUGIN: "true"
      GC_LANGUAGE: zh_CN
      GC_ACCESS_ADDRESS: 127.0.0.1
      GC_BIND_PORT: 443
      GC_ENABLE_CONSOLE: "false"
      GC_MONGODB_URL: mongodb://root:123456@mongo:27017
