name: Java

on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: ["main"]
    paths: ["*.java"]
  workflow_dispatch:

jobs:
  job_1:
    name: build server
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Initialize project
        run: git clone https://github.com/Grasscutters/Grasscutter.git app --depth=1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: grasscutter
          path: app/*.jar

  job_2:
    name: build plugin
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Initialize project
        run: git clone https://github.com/jie65535/gc-opencommand-plugin.git app --depth=1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: grasscutter
      - name: Set lib
        run: cd app && chmod +x gradlew && mkdir lib && mv ../*.jar ./lib
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: opencommand
          path: app/*.jar

  job_3:
    name: upload resource
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Initialize project
        run: git clone https://github.com/tamilpp25/Grasscutter_Resources.git app --depth=1
      - name: Build with Zip
        run: |
          mv grasscutter/*.jar ./grasscutter.jar
          mv opencommand/*.jar ./opencommand.jar
          cd app/Resources
          zip -rq resources.zip *
          mv *.zip ../..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            *.jar
            *.zip
