name: Java

on:
  push:
    branches: ["main"]
    paths: ["*.java"]
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java-version: ["18"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: Initialize project
        run: git clone https://github.com/Grasscutters/Grasscutter.git app --depth=1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: grasscutter
          path: app/*.jar

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Initialize project
        run: git clone https://github.com/Koko-boya/Grasscutter_Resources.git tmp --depth=1
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resources
          path: tmp/Resources/*
