name: Python

on:
  push:
    branches: [ "main" ]
    paths: [ "*.py" ]
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Initialize project
        run: |
          git clone https://github.com/Womsxd/AutoMihoyoBBS.git app --depth=1
          echo "${{ secrets.BOT_01 }}" > app/config/bot_1.yaml
          echo "${{ secrets.BOT_02 }}" > app/config/bot_2.yaml
          echo "${{ secrets.BOT_03 }}" > app/config/bot_3.yaml
          echo "${{ secrets.PUSH_INI }}" > app/config/push.ini
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Build and Run
        run: python app/main_multi.py autorun
