name: Python CI

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize project
        run: |
          git clone https://github.com/Womsxd/AutoMihoyoBBS.git app --depth=1
          echo "${{ secrets.BOT_01 }}" > app/config/bot_1.yaml
          echo "${{ secrets.BOT_02 }}" > app/config/bot_2.yaml
          echo "${{ secrets.BOT_03 }}" > app/config/bot_3.yaml
          echo "${{ secrets.PUSH_INI }}" > app/config/push.ini
      - name: Install Dependencies
        run: pip install -r app/requirements.txt
      - name: Running
        run: python app/main_multi.py autorun
